groups:
- name: ec2-alerts
  rules:
  - alert: HighCPUUage
    expr: avg(rate(node_cpu_seconds_total{mode !="idle"}[2m]))*100>80
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage detected"
      description: "CPU usage is above 80% for more than 2 minutes."  
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
     severity: critical
    annotations:
      summary: "EC2 Instance Down"
      description: "An EC2 instance is down for more than 1 minute."